services:
  - type: web
    name: shl-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: shl-frontend
    runtime: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
